# Generated by Django 5.1.2 on 2024-11-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_storeinfo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
