# Generated by Django 5.1.2 on 2024-11-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_storeinfo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
